function(setup_platform_detection TARGET_NAME)
    if (WIN32)
        if (CMAKE_SIZEOF_VOID_P EQUAL 8)
            target_compile_definitions(${TARGET_NAME} PUBLIC WINDOWS_X64)
            message(WARNING "Windows x64 is not fully supported, there might be errors.")
        else ()
            target_compile_definitions(${TARGET_NAME} PUBLIC WINDOWS_X86)
            message(FATAL_ERROR "Windows x86 support is not yet available.")
        endif ()
    elseif (APPLE)
        if (IOS)
            target_compile_definitions(${TARGET_NAME} PUBLIC IOS)
            message(FATAL_ERROR "IOS support is not yet available.")
        elseif (CMAKE_OSX_SYSROOT MATCHES ".*simulator.*")
            target_compile_definitions(${TARGET_NAME} PUBLIC IPHONE_SIMULATOR)
            message(FATAL_ERROR "IOS Simulator support is not yet available.")
        else ()
            target_compile_definitions(${TARGET_NAME} PUBLIC MACOS)
        endif ()
    elseif (ANDROID)
        target_compile_definitions(${TARGET_NAME} PUBLIC ANDROID)
        message(FATAL_ERROR "Android support is not yet available.")
    elseif (UNIX AND NOT APPLE)
        target_compile_definitions(${TARGET_NAME} PUBLIC LINUX)
        message(WARNING "Linux is not fully supported, there might be errors.")
    else ()
        message(FATAL_ERROR "Unknown platform!")
    endif ()
endfunction()